export const CANAL_LIMITE_SENSORES_1 = '23YC8RS6DRHAJX93'
export const CANAL_LIMITE_SENSORES_2 = 'OKPJYMR8BY4DS76U'
export const CANAL_MANUAL_AUTOMATICO = 'GYEY7LPTK3JRKEP1'

export const THINGSPEAK_URL = 'https://api.thingspeak.com/'
